### ISSUE TITLE
Jekyll will only serve you once

### ISSUE THREAD

**Issue by embarpasaribu** [embarpasaribu/docker#1]
```shell
embar@jessie-personal-project:~$ docker run -v $(pwd)/blog:/blog -p 192.168.1.10:4000:4000 -it embarpasaribu/blog:latest /bin/bash

root@e26cda33cc9d:/blog# /bin/bash -l -c "rvm --version"
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /blog/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

Unknown ruby interpreter version (do not know how to handle): RUBY_VERSION.
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

root@e26cda33cc9d:/blog# /bin/bash -l -c "ruby --version"                                                                                                                                                                                     
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /blog/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

Unknown ruby interpreter version (do not know how to handle): RUBY_VERSION.
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

root@e26cda33cc9d:/blog# /bin/bash -l -c "jekyll serve --host:0.0.0.0"                                                                                                                                                                        
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /blog/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

Unknown ruby interpreter version (do not know how to handle): RUBY_VERSION.
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find jekyll-feed-0.8.0 in any of the sources (Bundler::GemNotFound)
        from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/spec_set.rb:88:in `map!'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/spec_set.rb:88:in `materialize'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/jekyll-3.3.0/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/jekyll-3.3.0/exe/jekyll:9:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/jekyll:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/jekyll:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by embarpasaribu** [comment]
When you quit from a container, the container will still be there.
Do not do run command for it to start. Run command will try to re-create it.
Do start command to start it again.

NOTE:
Always add "--name" to run a container. So the run command will complained about name.
And it easier to start a container with a name.

```shell
$ docker run -v $(pwd)/blog:/blog -p 192.168.1.10:4000:4000 --name blog -it embarpasaribu/blog:latest /bin/bash

container:/blog $ exit

embar@jessie-personal-project:~$ docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                     PORTS               NAMES
88f3019ec0f5        embarpasaribu/blog:latest   "/bin/bash"              16 minutes ago      Exited (0) 6 seconds ago                       blog

embar@jessie-personal-project:~$ docker start -ai blog

embar@jessie-personal-project:~$ docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                         NAMES
88f3019ec0f5        embarpasaribu/blog:latest   "/bin/bash"              17 minutes ago      Up 13 seconds       192.168.1.10:4000->4000/tcp   blog
```
